on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 11
          cache: gradle
      - run: |
          ./gradlew build --scan
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports from Gradle
          path: build/reports
