on:
  push:
    branches: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v3
      - use: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 11
          cache: gradle
      - run: |
          ./gradlew build --scan
